config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'
  get 'pages/index'
  get 'pages/contact'
  
  devise_for :users
  
  resources :subtasks

  resources :tasks

  resources :lists

  root to: redirect('/pages/index')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks

    validates :title, presence: true, uniqueness: true

    validates :description, presence: true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task

  validates :title, presence: true, uniqueness: true

  validates :description, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  has_many :subtasks

  validates :title, presence: true, uniqueness: true

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # has_secure_password

  devise :database_authenticatable, :registerable, :recoverable

  # attr_accessor :password_confirmation

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, length: { minimum: 6}
  # validate :password_match, on: :create

  # def password_match
  #   if encrypted_password != password_confirmation
  #     errors.add(:encrypted_password, "Password don't match")
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :get_list, only: %i(show update destroy edit)

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def show
  end

  private

  def get_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :description, :private, :favorit, :done)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :get_list, only: %i(show update destroy edit)

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def show
  end

  # private

  # def get_list
  #   @list = List.find(params[:id])
  # end

  # def list_params
  #   params.require(:list).permit(:title, :description, :private, :favorit, :done)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end

  def index
  end

  def contact
  end
  
end

app/controllers/subtask_controller.rb
class SubtaskController < ApplicationController
  def index
    @subtasks = Subtask.all
  end

  def new
    @subtask = Subtask.new
  end

  def create
    @subtask = Subtask.new(subtask_params)
    if @subtask.save
      redirect_to subtask_path(@subtask)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @subtask.update(subtask_params)

    redirect_to subsubtask_path(@subtask)
  end

  def show
  end

  private

  def get_subtask
    @subtask = subtask.find(params[:id])
  end

  def subtask_params
    params.require(:subtask).permit(:title, :description, :private, :favorit, :done)
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  def index
    @subtasks = Subtask.all
  end

  def new
    @subtask = Subtask.new
  end

  def create
    @subtask = Subtask.new(subtask_params)
    if @subtask.save
      redirect_to subtask_path(@subtask)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @subtask.update(subtask_params)

    redirect_to subsubtask_path(@subtask)
  end

  def show
  end

  private

  def get_subtask
    @subtask = subtask.find(params[:id])
  end

  def subtask_params
    params.require(:subtask).permit(:title, :description, :private, :favorit, :done)
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def show
  end

  private

  def get_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :private, :favorit, :done)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def show
  end

  private

  def get_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :private, :favorit, :done)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in_user, only: [:show, :edit, :update]

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = 'Cadastro realizado com sucesso'
        redirect_to root_url
      else
        render 'new'
      end
    end

    def edit; end
  
    def update
      if current_user.update(user_params)
        flash[:success] = 'Dados atualizados com sucesso'
        redirect_to user_contacts_url(current_user)
      else
        render 'edit'
      end
    end
  
    private

    def user_params
      params
        .require(:user)
        .permit(:name, :email, :encrypted_password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subtask_helper.rb
module SubtaskHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', "#" %>
      </li>
      <li>
        <%= link_to 'Contato', '#' %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'To-do List', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to 'Tasks', '#' %>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
     <% if user_signed_in?%>
        <li class="active">
          <%= link_to current_user.name.capitalize, '#' %>
        </li>
        <li class="active">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="active">
          <%= link_to 'Nova Conta', new_registration_path(resource_name) %>
        </li>
        <li>
          <%= link_to 'Entrar', new_session_path(resource_name) %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To-do List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/header' %>

   <div class="container">

     <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>

     <%= yield %>

     <%= render 'layouts/footer' %>
   </div>


 </body>
</html>

app/views/lists/create.html.erb
<h1>List#create</h1>
<p>Find me in app/views/list/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>List#destroy</h1>
<p>Find me in app/views/list/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>List#edit</h1>
<p>Find me in app/views/list/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>List#index</h1>
<p>Find me in app/views/list/index.html.erb</p>

app/views/lists/new.html.erb
<h1>List#new</h1>
<p>Find me in app/views/list/new.html.erb</p>

app/views/lists/show.html.erb
<h1>List#show</h1>
<p>Find me in app/views/list/show.html.erb</p>

app/views/lists/update.html.erb
<h1>List#update</h1>
<p>Find me in app/views/list/update.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href="http://www.twitter.com/lukberringer">@lukberringer</a> para saber mais.
</p>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>To-do List - Public</h1>
  <p>
    Aqui ficarão as listas públicas
  </p>
  <p>
    <%= link_to 'Crie Sua Conta', '#', class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/pages/info.html.erb
<h1>Info</h1>

<p>
Esta é uma to_do list produzida por Lucas Guidi
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/subtasks/create.html.erb
<h1>Subtask#create</h1>
<p>Find me in app/views/subtask/create.html.erb</p>

app/views/subtasks/destroy.html.erb
<h1>Subtask#destroy</h1>
<p>Find me in app/views/subtask/destroy.html.erb</p>

app/views/subtasks/edit.html.erb
<h1>Subtask#edit</h1>
<p>Find me in app/views/subtask/edit.html.erb</p>

app/views/subtasks/index.html.erb
<h1>Subtask#index</h1>
<p>Find me in app/views/subtask/index.html.erb</p>

app/views/subtasks/new.html.erb
<h1>Subtask#new</h1>
<p>Find me in app/views/subtask/new.html.erb</p>

app/views/subtasks/show.html.erb
<h1>Subtask#show</h1>
<p>Find me in app/views/subtask/show.html.erb</p>

app/views/subtasks/update.html.erb
<h1>Subtask#update</h1>
<p>Find me in app/views/subtask/update.html.erb</p>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Task#destroy</h1>
<p>Find me in app/views/task/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Task#edit</h1>
<p>Find me in app/views/task/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Task#index</h1>
<p>Find me in app/views/task/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Task#new</h1>
<p>Find me in app/views/task/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Task#show</h1>
<p>Find me in app/views/task/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :encrypted_password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Cadastro</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @user do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>